import os
import glob
import html
from flask import Flask, request, jsonify, render_template, send_file
from werkzeug.utils import secure_filename
try:
    from weasyprint import HTML, CSS
    WEASYPRINT_AVAILABLE = True
    WEASYPRINT_ERROR = None
except (OSError, ImportError) as e:
    WEASYPRINT_AVAILABLE = False
    WEASYPRINT_ERROR = str(e)
from pygments import highlight
from pygments.lexers import get_lexer_for_filename
from pygments.formatters import HtmlFormatter
from pygments.util import ClassNotFound
import io
import mimetypes

app = Flask(__name__)

def is_text_file(filepath):
    """Attempt to guess if a file is a text/code file."""
    # Ignore obvious binaries based on extension
    mime_type, _ = mimetypes.guess_type(filepath)
    if mime_type and not mime_type.startswith('text/') and mime_type not in ['application/json', 'application/javascript', 'application/xml']:
        # Some code files might not strictly drop into text/* by mimetypes but are code
        # Let's do a simple check on extension
        ext = os.path.splitext(filepath)[1].lower()
        allowed_extensions = {
            '.py', '.js', '.html', '.css', '.md', '.txt', '.csv', '.json', '.xml', '.yml', '.yaml',
            '.sh', '.bat', '.ps1', '.c', '.cpp', '.cxx', '.h', '.hpp', '.hxx', '.java', '.cs', '.php',
            '.go', '.rs', '.rb', '.ts', '.jsx', '.tsx', '.sql', '.kt', '.swift', '.scala', '.m', '.r',
            '.lua', '.pl', '.pm', '.dart', '.vue', '.svelte', '.toml', '.ini', '.cfg', '.conf', '.env'
        }
        if ext not in allowed_extensions:
            return False
    return True

@app.route('/')
def index():
    """Render the main frontend interface."""
    return render_template('index.html')


@app.route('/api/scan-directory', methods=['POST'])
def scan_directory():
    """
    Scans a given absolute directory path for readable text/code files.
    Skips hidden folders (e.g., .git) and binary files.
    """
    data = request.json
    if not data or 'path' not in data:
        return jsonify({'error': 'Missing directory path parameter.'}), 400
        
    dir_path = data['path'].strip()
    
    if not os.path.isdir(dir_path):
        return jsonify({'error': 'Invalid directory path or directory does not exist.'}), 400
        
    file_list = []
    
    try:
        for root, dirs, files in os.walk(dir_path):
            # Ignore hidden directories (e.g. .git, .env)
            dirs[:] = [d for d in dirs if not d.startswith('.')]
            
            for file in files:
                # Ignore hidden files
                if file.startswith('.'):
                    continue
                    
                filepath = os.path.join(root, file)
                
                # Check if it's likely a text file
                if not is_text_file(filepath):
                    continue
                    
                rel_path = os.path.relpath(filepath, dir_path)
                file_ext = os.path.splitext(file)[1]
                
                file_list.append({
                    'absolute_path': filepath,
                    'relative_path': rel_path,
                    'filename': file,
                    'extension': file_ext
                })
                
        # Sort files by relative path
        file_list.sort(key=lambda x: x['relative_path'].lower())
        
        return jsonify({'files': file_list, 'scanned_path': dir_path})
        
    except Exception as e:
        return jsonify({'error': f'An error occurred while scanning: {str(e)}'}), 500


@app.route('/api/generate-pdf', methods=['POST'])
def generate_pdf():
    """
    Accepts a list of absolute file paths, reads their contents, applies syntax highlighting,
    and returns a PDF generated by WeasyPrint.
    """
    if not WEASYPRINT_AVAILABLE:
        return jsonify({
            'error': f'PDF generation is disabled because WeasyPrint dependencies (GTK3/Pango) are missing or conflicting on your system. Please see the README or use Docker for Windows natively.\n\nDetails: {WEASYPRINT_ERROR}'
        }), 500

    data = request.json
    if not data or 'files' not in data:
        return jsonify({'error': 'Missing files list parameter.'}), 400
        
    files_to_process = data['files']
    if not files_to_process:
        return jsonify({'error': 'No files selected to process.'}), 400
        
    settings = data.get('settings', {})
    doc_title = settings.get('title', 'Code Export')
    theme = settings.get('theme', 'monokai')
    font_family = settings.get('font', "'Courier New', Courier, monospace")
    font_size = settings.get('size', '10pt')
    paper_size_setting = settings.get('paper', 'A4')
    show_linenos = settings.get('linenos', True)
    
    # Handle custom paper size
    if paper_size_setting == 'Custom':
        custom_w = settings.get('customWidth', '8.5in')
        custom_h = settings.get('customHeight', '11in')
        paper_size = f"{custom_w} {custom_h}"
    else:
        paper_size = paper_size_setting
        
    # Determine base background color based on theme
    # Fallbacks if theme isn't strictly recognized but pygments has many built-in
    bg_color = "#ffffff"
    text_color = "#333333"
    
    if theme in ['monokai', 'dracula', 'github-dark']:
        bg_color = "#272822" if theme == 'monokai' else ("#282a36" if theme == 'dracula' else "#0d1117")
        text_color = "#f8f8f2" if theme in ['monokai', 'dracula'] else "#c9d1d9"
        
    # HTML Content building
    html_content = ["<html><head><meta charset='utf-8'>"]
    
    # 1. Add Pygments CSS
    pygments_linenos_mode = 'inline' if show_linenos else False
    try:
        formatter = HtmlFormatter(style=theme, linenos=pygments_linenos_mode, cssclass="source")
    except ClassNotFound:
        formatter = HtmlFormatter(style='default', linenos=pygments_linenos_mode, cssclass="source")
        
    pygments_css = formatter.get_style_defs('.source')
    html_content.append(f"<style>{pygments_css}</style>")
    
    # 2. Add WeasyPrint Pagination and base styles
    html_content.append(f"""
    <style>
        @page {{
            size: {paper_size};
            margin: 2cm;
            @bottom-right {{
                content: "Page " counter(page) " of " counter(pages);
                font-family: sans-serif;
                font-size: 9pt;
                color: #888;
            }}
        }}
        body {{
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 11pt;
            background-color: {bg_color};
            color: {text_color};
            margin: 0;
            padding: 0;
        }}
        h1.doc-title {{
            text-align: center;
            font-size: 28pt;
            margin-top: 30vh;
            margin-bottom: 2em;
            color: inherit;
        }}
        h2.file-header {{
            font-size: 14pt;
            margin-top: 2em;
            margin-bottom: 1em;
            padding-bottom: 5px;
            border-bottom: 1px solid #888; 
            color: inherit;
            word-break: break-all;
            page-break-after: avoid;
        }}
        .file-section {{
            margin-bottom: 30px;
        }}
        .file-section:not(:first-child) {{
            page-break-before: always;
            border-top: none;
        }}
        /* Style for Pygments output block */
        .source {{
            background-color: {bg_color};
            border-radius: 4px;
            padding: 10px;
            overflow-x: auto;
            /* CRITICAL: Avoid page breaks inside code blocks if possible, but allow for lines */
            page-break-inside: auto; 
        }}
        .source pre {{
            margin: 0;
            font-family: {font_family};
            font-size: {font_size};
            white-space: pre-wrap; /* allow wrapping for long lines */
            word-wrap: break-word; /* ensure long words don't overflow */
        }}
        .code-line {{
            display: block;
            padding-left: 60px;
            text-indent: -60px;
        }}
        .linenos {{
            display: inline-block;
            width: 40px;
            padding-right: 10px;
            text-align: right;
            color: #888;
            border-right: 1px solid #888;
            margin-right: 9px; /* total pulled back by exactly 60px */
            user-select: none;
        }}
        /* Try to prevent page breaks inside individual lines or tokens if possible */
        .source pre span {{
            page-break-inside: avoid;
        }}
        .error-note {{
            color: #e6db74; /* monokai yellow */
            font-style: italic;
        }}
    </style>
    </head><body>
    """)
    
    html_content.append(f"<h1 class='doc-title'>{html.escape(doc_title)}</h1>")
    
    for filepath in files_to_process:
        if not os.path.exists(filepath):
            html_content.append(f"<div class='file-section'><h2 class='file-header'>{filepath}</h2><p class='error-note'>Error: File not found.</p></div>")
            continue
            
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                code_content = f.read()
                
            # Try to guess lexer
            try:
                lexer = get_lexer_for_filename(filepath)
            except ClassNotFound:
                # Fallback lexer (Text)
                from pygments.lexers.special import TextLexer
                lexer = TextLexer()
                
            highlighted_code = highlight(code_content, lexer, formatter)
            
            if show_linenos:
                highlighted_code = highlighted_code.replace('<span class="linenos">', '<div class="code-line"><span class="linenos">')
                lines = highlighted_code.split('\n')
                for i, line in enumerate(lines):
                    if '<div class="code-line">' in line:
                        if '</pre>' in line:
                            lines[i] = line.replace('</pre>', '</div></pre>')
                        else:
                            lines[i] = line + '</div>'
                # Rejoin with empty string since DIV is block level and adds its own break
                highlighted_code = ''.join(lines)
            
            html_content.append(f"<div class='file-section'>")
            html_content.append(f"<h2 class='file-header'>{filepath}</h2>")
            html_content.append(highlighted_code)
            html_content.append("</div>")
            
        except UnicodeDecodeError:
            # Handle non-utf8 readable files gracefully
            html_content.append(f"<div class='file-section'><h2 class='file-header'>{filepath}</h2><p class='error-note'>Error: File encoding not supported (could not decode as UTF-8).</p></div>")
        except Exception as e:
            html_content.append(f"<div class='file-section'><h2 class='file-header'>{filepath}</h2><p class='error-note'>Error: {str(e)}</p></div>")
            
    html_content.append("</body></html>")
    joined_html = "\n".join(html_content)
    
    # Generate PDF via WeasyPrint
    try:
        pdf_bytes = HTML(string=joined_html).write_pdf()
        
        # Return PDF to frontend
        return send_file(
            io.BytesIO(pdf_bytes),
            mimetype='application/pdf',
            as_attachment=True,
            download_name='code_export.pdf'
        )
    except Exception as e:
        print(f"Weasyprint error: {str(e)}")
        return jsonify({'error': f'Failed to generate PDF: {str(e)}'}), 500


if __name__ == '__main__':
    app.run(debug=True, port=5000)
